### ISSUE TITLE
Make extension available in Raycast Store

### ISSUE THREAD

**Issue by ylansegal** [BalliAsghar/menu-bar-search-raycast#1]
@BalliAsghar Thank you so much for making this extension! I recently switched from Alfred.app to Raycast, and would not have done so without your extension. To me, that is the killer feature, because it allows me to have a command palette for **every** app. 

Have you considered publishing the extension in the official [Raycast Store](https://www.raycast.com/store)? I was able to install the extension by cloning the repo and using `npm`. I am a software engineer and had all the tooling installed. However, I that won't be the case for all Raycast users that can benefit from your extension. In particular, I am thinking of my family members. 

Thanks again for your work, and for making it available!

**Comment by BalliAsghar** [comment]
@ylansegal Thank you for your kind words! I'm glad you found the extension helpful. Just a heads up, Raycast has a built-in extension called "Search Menu Items" that provides similar functionality. I created this extension before I was aware of that. 
Appreciate your support!

**Comment by ylansegal** [comment]
Oh... fantastic. Thank you! I'll check that out.

**Comment by youtextme** [comment]
Nice — Alfred → Raycast Store ask is the right move.

Meanwhile you can often sideload from the repo (**Import Extension** / local dev) so menu-bar search is not blocked on review. Dual-hotkey still helps if any Alfred snippets remain.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro. Free tier is enough for Store + this extension once listed.
